frr version 8.0
frr defaults traditional
hostname frr-bgp-router
log syslog informational
no ipv6 forwarding
!
router bgp 65001
 bgp router-id 172.20.0.2
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
!
 neighbor 172.20.0.3 remote-as 65002
 neighbor 172.20.0.3 description Ryu-SDN-Controller
 neighbor 172.20.0.3 timers 10 30
 neighbor 172.20.0.3 timers connect 10
!
 address-family ipv4 unicast
  network 192.168.10.0/24
  network 192.168.20.0/24
  network 192.168.30.0/24
  neighbor 172.20.0.3 activate
  neighbor 172.20.0.3 soft-reconfiguration inbound
 exit-address-family
!
line vty
!